<a href="https://colab.research.google.com/github/mohamedzaghloul-lab638/-Drug-Activity-Prediction-pIC50-/blob/main/qsar_modelling_for_trpa1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.4)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.6 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 5.1 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.6 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.1.0 chembl_webresource_client-0.10.9 requests-cache-1.3.1 url-normalize-2.2.1

In [ ]:
from chembl_webresource_client.new_client import new_client
import pandas as pd

In [ ]:
target=new_client.target
res=target.search('TRPA1')
for r in res :
  print(r['target_chembl_id'])
  print(r['organism'])
  print(r['pref_name'])
  print(r['target_type'])

df=pd.DataFrame(list(res))
print(len(df))
df

CHEMBL6007
Homo sapiens
Transient receptor potential cation channel subfamily A member 1
SINGLE PROTEIN
CHEMBL4524031
Cavia porcellus
ANK_REP_REGION domain-containing protein
SINGLE PROTEIN
CHEMBL6066835
Macaca mulatta
Transient receptor potential cation channel subfamily A member 1
SINGLE PROTEIN
CHEMBL5160
Rattus norvegicus
Transient receptor potential cation channel subfamily A member 1
SINGLE PROTEIN
CHEMBL1075310
Mus musculus
Transient receptor potential cation channel subfamily A member 1
SINGLE PROTEIN
5

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Transient receptor potential cation channel su...,14.0,False,CHEMBL6007,"[{'accession': 'O75762', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Cavia porcellus,ANK_REP_REGION domain-containing protein,14.0,False,CHEMBL4524031,"[{'accession': 'H0VJD1', 'component_descriptio...",SINGLE PROTEIN,10141
2,[],Macaca mulatta,Transient receptor potential cation channel su...,14.0,False,CHEMBL6066835,"[{'accession': 'A0A1D5QMT1', 'component_descri...",SINGLE PROTEIN,9544
3,[],Rattus norvegicus,Transient receptor potential cation channel su...,13.0,False,CHEMBL5160,"[{'accession': 'Q6RI86', 'component_descriptio...",SINGLE PROTEIN,10116
4,[],Mus musculus,Transient receptor potential cation channel su...,13.0,False,CHEMBL1075310,"[{'accession': 'Q8BLA8', 'component_descriptio...",SINGLE PROTEIN,10090

In [ ]:
human_targets = df[df['organism'] == 'Homo sapiens']
for index, row in human_targets.iterrows():
    print(f"id is: {row['target_chembl_id']}")

id is: CHEMBL6007

In [ ]:
# search for all active compounds against TRPA1
activity = new_client.activity
results=activity.filter (
    target_chembl_id ='CHEMBL6007',
    standard_type='IC50' ,
    relation='=' ,
    assay_type="B" ) .only([
        'canonical_smiles'
        'standard_value'
        'standard_units'
        'molecule_chembl_id'
        'assay_chembl_id'


    ])

df=pd.DataFrame(list(results))
df

,assay_chembl_id,canonical_smiles,molecule_chembl_id,standard_units,standard_value,units,value
0,CHEMBL2328091,CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1,CHEMBL1086310,nM,6200.0,uM,6.2
1,CHEMBL2422134,Cc1sc(Nc2ccc(Cl)cc2F)nc1C(=O)N1CCC[C@H](C)[C@@...,CHEMBL2418811,nM,25000.0,nM,25000.0
2,CHEMBL2422134,Cc1ccc(Nc2nc(C(=O)N3CCCC(C)C3C)cs2)cc1,CHEMBL2418806,nM,8000.0,nM,8000.0
3,CHEMBL2433975,CCC/C=C1\OC(=O)c2ccccc21,CHEMBL249592,nM,23000.0,uM,23.0
4,CHEMBL3222891,Cc1c(=O)n(Cc2ccccc2)c(=O)n2cc(C(=O)NCc3ccc4[nH...,CHEMBL3220224,nM,680.0,nM,680.0
...,...,...,...,...,...,...,...
2069,CHEMBL5739380,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(Cl)ccc5o4)n3...,CHEMBL5171677,nM,12.0,nM,12.0
2070,CHEMBL5739380,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(F)ccc5o4)n3)...,CHEMBL5766384,nM,18.0,nM,18.0
2071,CHEMBL5739380,CC1NN(C)c2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21,CHEMBL5757346,nM,366.0,nM,366.0
2072,CHEMBL5739380,Cn1nnc2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21,CHEMBL5891037,nM,1120.0,nM,1120.0
2073,CHEMBL5739380,O=c1c2cccnc2ncn1Cc1nc(CC(O)c2ccc(Cl)cc2)no1,CHEMBL3786639,nM,52.0,nM,52.0

In [ ]:
print(len(results))

2074

In [ ]:
df_leads=df.dropna(subset=['molecule_chembl_id','standard_value','canonical_smiles']).drop(columns=['assay_chembl_id', 'standard_units','units','value'])
print(len(df_leads))
df_leads

2067

,canonical_smiles,molecule_chembl_id,standard_value
0,CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1,CHEMBL1086310,6200.0
1,Cc1sc(Nc2ccc(Cl)cc2F)nc1C(=O)N1CCC[C@H](C)[C@@...,CHEMBL2418811,25000.0
2,Cc1ccc(Nc2nc(C(=O)N3CCCC(C)C3C)cs2)cc1,CHEMBL2418806,8000.0
3,CCC/C=C1\OC(=O)c2ccccc21,CHEMBL249592,23000.0
4,Cc1c(=O)n(Cc2ccccc2)c(=O)n2cc(C(=O)NCc3ccc4[nH...,CHEMBL3220224,680.0
...,...,...,...
2069,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(Cl)ccc5o4)n3...,CHEMBL5171677,12.0
2070,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(F)ccc5o4)n3)...,CHEMBL5766384,18.0
2071,CC1NN(C)c2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21,CHEMBL5757346,366.0
2072,Cn1nnc2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21,CHEMBL5891037,1120.0
2073,O=c1c2cccnc2ncn1Cc1nc(CC(O)c2ccc(Cl)cc2)no1,CHEMBL3786639,52.0

In [ ]:
# ic50 to pic50
import numpy as np
df_leads['standard_value'] = pd.to_numeric(df_leads['standard_value'], errors='coerce')
df_leads['PIC50'] = -np.log10(df_leads['standard_value'] * 1e-9)
df_leads

,canonical_smiles,molecule_chembl_id,standard_value,PIC50
0,CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1,CHEMBL1086310,6200.0,5.207608
1,Cc1sc(Nc2ccc(Cl)cc2F)nc1C(=O)N1CCC[C@H](C)[C@@...,CHEMBL2418811,25000.0,4.602060
2,Cc1ccc(Nc2nc(C(=O)N3CCCC(C)C3C)cs2)cc1,CHEMBL2418806,8000.0,5.096910
3,CCC/C=C1\OC(=O)c2ccccc21,CHEMBL249592,23000.0,4.638272
4,Cc1c(=O)n(Cc2ccccc2)c(=O)n2cc(C(=O)NCc3ccc4[nH...,CHEMBL3220224,680.0,6.167491
...,...,...,...,...
2069,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(Cl)ccc5o4)n3...,CHEMBL5171677,12.0,7.920819
2070,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(F)ccc5o4)n3)...,CHEMBL5766384,18.0,7.744727
2071,CC1NN(C)c2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21,CHEMBL5757346,366.0,6.436519
2072,Cn1nnc2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21,CHEMBL5891037,1120.0,5.950782
2073,O=c1c2cccnc2ncn1Cc1nc(CC(O)c2ccc(Cl)cc2)no1,CHEMBL3786639,52.0,7.283997

In [ ]:
# add feautres to smiles
! pip install rdkit

Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2025.9.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)

In [ ]:
from rdkit import Chem
from rdkit.Chem import Descriptors , rdMolDescriptors

def get_feautres(smiles):
  mol=Chem.MolFromSmiles(smiles)
  if mol is None :
     return None
  return {
       'TPSA' :Descriptors.TPSA(mol),
       'Logp' : Descriptors.MolLogP(mol),
       'MolWt' : Descriptors.MolWt(mol),
       'HBA' : rdMolDescriptors.CalcNumHBA(mol),
       'HBD' : rdMolDescriptors.CalcNumHBD(mol),
       'RotBonds' : Descriptors.NumRotatableBonds(mol)
   }

df_features = df_leads['canonical_smiles'].apply (get_feautres).apply(pd.Series) # here we copy features to our smiles
# concatenation of PIC50 with features df (smiles + features)
df_model=pd.concat([df_features , df_leads[['PIC50' , 'canonical_smiles']]] , axis =1)

In [ ]:
df_model.dropna(inplace=True)
df_model

,TPSA,Logp,MolWt,HBA,HBD,RotBonds,PIC50,canonical_smiles
0,90.92,1.19580,355.398,4.0,1.0,4.0,5.207608,CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1
1,45.23,5.24822,381.904,4.0,1.0,3.0,4.602060,Cc1sc(Nc2ccc(Cl)cc2F)nc1C(=O)N1CCC[C@H](C)[C@@...
2,45.23,4.45572,329.469,4.0,1.0,3.0,5.096910,Cc1ccc(Nc2nc(C(=O)N3CCCC(C)C3C)cs2)cc1
3,26.30,2.99800,188.226,2.0,0.0,2.0,4.638272,CCC/C=C1\OC(=O)c2ccccc21
4,88.37,3.29072,444.516,4.0,2.0,5.0,6.167491,Cc1c(=O)n(Cc2ccccc2)c(=O)n2cc(C(=O)NCc3ccc4[nH...
...,...,...,...,...,...,...,...,...
2069,168.09,1.56482,469.845,9.0,2.0,6.0,7.920819,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(Cl)ccc5o4)n3...
2070,168.09,1.05052,453.390,9.0,2.0,6.0,7.744727,Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(F)ccc5o4)n3)...
2071,93.76,1.18960,386.847,7.0,1.0,5.0,6.436519,CC1NN(C)c2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21
2072,109.20,0.45590,371.792,7.0,0.0,5.0,5.950782,Cn1nnc2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21
2073,106.93,2.15230,383.795,7.0,1.0,5.0,7.283997,O=c1c2cccnc2ncn1Cc1nc(CC(O)c2ccc(Cl)cc2)no1

In [ ]:
from rdkit.Chem import rdFingerprintGenerator

In [ ]:
def smiles_to_fps(smiles, radius=2, fpsize=2048):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    gen = rdFingerprintGenerator.GetMorganGenerator(radius, fpSize=fpsize)
    fp = gen.GetFingerprint(mol)
    return np.array(fp)

df_model['fingerprint'] = df_model['canonical_smiles'].apply(smiles_to_fps)
df_model = df_model.dropna(subset=['fingerprint'])

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

x= np.stack(df_model['fingerprint'])
y= df_model['PIC50'].values

# splitting
x_train , x_test,y_train , y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=RandomForestRegressor(n_estimators=200,random_state=42 , max_depth=10 , n_jobs=-1 )# use all cpus
model.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, n_jobs=-1,
                      random_state=42)

In [ ]:
# evaluation
y_pred=model.predict(x_test)
r2=r2_score(y_test , y_pred)
mse=np.sqrt(mean_squared_error(y_test , y_pred))
print(f"R2 score is : {r2:.3f}")
print(f"mse is: {mse:.3f}")

R2 score is : 0.637
mse is: 0.548

In [ ]:
descriptors = df_model[['MolWt', 'Logp', 'TPSA', 'HBA', 'HBD', 'RotBonds']].values
fps = np.stack(df_model['fingerprint'])

x = np.hstack([fps, descriptors])
y= df_model['PIC50'].values

# splitting
x_train , x_test,y_train , y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=RandomForestRegressor(n_estimators=200,random_state=42 , max_depth=10 , n_jobs=-1 )# use all cpus
model.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, n_estimators=200, n_jobs=-1,
                      random_state=42)

In [ ]:
# evaluation
y_pred=model.predict(x_test)
r2=r2_score(y_test , y_pred)
mse=np.sqrt(mean_squared_error(y_test , y_pred))
print(f"R2 score is : {r2:.3f}")
print(f"mse is: {mse:.3f}")

R2 score is : 0.681
mse is: 0.514

In [ ]:
# using XGBoost
from xgboost import XGBRegressor
model=XGBRegressor(learning_rate=0.05 , subsample=0.8 , colsample_bytree=0.8 , random_state=42 , verbosity=0, max_depth=10)
model.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=10,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
# evaluation
y_pred=model.predict(x_test)
r2=r2_score(y_test , y_pred)
mse=np.sqrt(mean_squared_error(y_test , y_pred))
print(f"R2 score is : {r2:.3f}")
print(f"mse is: {mse:.3f}")

R2 score is : 0.719
mse is: 0.482

In [ ]:
from sklearn.model_selection import GridSearchCV

params = {
    'n_estimators': [300, 500, 700],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

grid = GridSearchCV(XGBRegressor(random_state=42),
                    params, cv=5, scoring='r2', n_jobs=-1)
grid.fit(x_train, y_train)
print("Best R2:", grid.best_score_)
print("Best Params:", grid.best_params_)

Best R2: 0.6762204097536022
Best Params: {'colsample_bytree': 1.0, 'learning_rate': 0.05, 'max_depth': 6, 'n_estimators': 500, 'subsample': 0.8}

In [ ]:
# evaluation of grid
y_pred=grid.predict(x_test)
r2=r2_score(y_test , y_pred)
mse=np.sqrt(mean_squared_error(y_test , y_pred))
print(f"R2 score is : {r2:.3f}")
print(f"mse is: {mse:.3f}")

R2 score is : 0.733
mse is: 0.470

In [ ]:
import joblib
joblib.dump(grid, 'pic50_model.pkl')

['pic50_model.pkl']

In [ ]:
# prediction
from rdkit import Chem
from rdkit.Chem import Descriptors , rdFingerprintGenerator
import numpy as np
import pandas as pd

In [ ]:
df_smiles = pd.read_excel('/content/smiles.xlsx')
df_smiles.to_csv('file.csv', index=False)
df_smiles

                                              smiles           compound
0  COC1=C(C(=C2C(=C1)OC(=CC2=O)C3=CC=C(C=C3)O)O)O...       Crismaritin
1  C1=CC=C(C=C1)C2=CC(=O)C3=C(C=CC(=C3O2)O)O     ...          Primetin
2  CC(C)C[C@@H](C1=C(C(=C(C(=C1O)C=O)O)C=O)O)[C@]...     Macrocarpal A
3  OC1=C(C(CC(C)C)=O)C(O)=C(CC2=C(O)C(C(CC(C)C)=O...         Jensenal
4  C[C@@H]1CC[C@@]2(CC[C@@]3(C(=CC[C@H]4[C@]3(CC[...       Asiatic acid
5  C[C@@H]1[C@H]2C3=CCC4[C@]5(C[C@H]([C@@H]([C@@]...     Guavenoic acid
6  CC1=CC(=O)C2=C(C=C(C=C2O1)O[C@H]3[C@@H]([C@H](...    Cypellocarpin C
7  C1=CC(=C(C=C1C[C@H](C(=O)O)OC(=O)/C=C/C2=CC(=C...  Rosmarinic acid
8  C1=C2C3=C(C(=C1O)O)OC(=O)C4=CC(=C(C(=C43)OC2=O...      Ellagic acid
9  C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O[C...        Avicularin

In [ ]:
def predict_features(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    # Calculate descriptors
    tpsa = Descriptors.TPSA(mol)
    logp = Descriptors.MolLogP(mol)
    molwt = Descriptors.MolWt(mol)
    hba = rdMolDescriptors.CalcNumHBA(mol)
    hbd = rdMolDescriptors.CalcNumHBD(mol)
    rotbonds = Descriptors.NumRotatableBonds(mol)
    descriptors = np.array([molwt, logp, tpsa, hba, hbd, rotbonds])

    # Generate fingerprints
    gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)
    fp = gen.GetFingerprint(mol)
    fingerprint = np.array(fp)

    # Combine features
    combined_features = np.hstack([fingerprint, descriptors])
    return combined_features.reshape(1, -1)

In [ ]:
# Load the trained model
import joblib
model = joblib.load('pic50_model.pkl')
prediction_data=[]
df_clean = df.dropna(subset=['canonical_smiles'])

for smiles in df_clean['canonical_smiles']:
    combined_features = predict_features(smiles)
    if combined_features is None:
        continue

    predicted_pic50 = model.predict(combined_features)[0]
    prediction_data.append({
        'canonical_smiles': smiles.strip(),
        'predicted_PIC50': predicted_pic50
        })

predictions_df = pd.DataFrame(prediction_data)
print(predictions_df)

                                       canonical_smiles  predicted_PIC50
0       CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1         5.092434
1     Cc1sc(Nc2ccc(Cl)cc2F)nc1C(=O)N1CCC[C@H](C)[C@@...         4.804754
2                Cc1ccc(Nc2nc(C(=O)N3CCCC(C)C3C)cs2)cc1         5.055934
3                              CCC/C=C1\OC(=O)c2ccccc21         4.735633
4     Cc1c(=O)n(Cc2ccccc2)c(=O)n2cc(C(=O)NCc3ccc4[nH...         6.038754
...                                                 ...              ...
2062  Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(Cl)ccc5o4)n3...         7.806986
2063  Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(F)ccc5o4)n3)...         7.675134
2064    CC1NN(C)c2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21         6.484612
2065       Cn1nnc2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21         6.333217
2066        O=c1c2cccnc2ncn1Cc1nc(CC(O)c2ccc(Cl)cc2)no1         7.184896

[2067 rows x 2 columns]

In [ ]:
from google.colab import files
predictions_df.to_csv('predictions.csv', index=False)

In [ ]:
files.download('predictions.csv')

In [ ]:
# IC50 in M
predictions_df['IC50_M'] = 10 ** (-predictions_df['predicted_PIC50'])

# IC50 in nM
predictions_df['IC50_nM'] = predictions_df['IC50_M'] * 1e9

print(predictions_df[['canonical_smiles', 'predicted_PIC50', 'IC50_nM']])

                                       canonical_smiles  predicted_PIC50  \
0       CC(C)c1ccc(NC(=O)Cn2cnc3c2c(=O)n(C)c(=O)n3C)cc1         5.092434
1     Cc1sc(Nc2ccc(Cl)cc2F)nc1C(=O)N1CCC[C@H](C)[C@@...         4.804754
2                Cc1ccc(Nc2nc(C(=O)N3CCCC(C)C3C)cs2)cc1         5.055934
3                              CCC/C=C1\OC(=O)c2ccccc21         4.735633
4     Cc1c(=O)n(Cc2ccccc2)c(=O)n2cc(C(=O)NCc3ccc4[nH...         6.038754
...                                                 ...              ...
2062  Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(Cl)ccc5o4)n3...         7.806986
2063  Cc1oc2ncn(Cc3nnn(C[C@H](O)c4cc5cc(F)ccc5o4)n3)...         7.675134
2064    CC1NN(C)c2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21         6.484612
2065       Cn1nnc2ncn(Cc3nnn(CCc4ccc(Cl)cc4)n3)c(=O)c21         6.333217
2066        O=c1c2cccnc2ncn1Cc1nc(CC(O)c2ccc(Cl)cc2)no1         7.184896

           IC50_nM
0      8082.870605
1     15676.396484
2      8791.552734
3     18380.892578
4       914.630249
...            ...
2062     15.596015
2063     21.128384
2064    327.633636
2065    464.283081
2066     65.328629

[2067 rows x 3 columns]

In [ ]:
prediction_new=predictions_df.to_csv('prediction_new.csv',index=False)
files.download('prediction_new.csv')